services:
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: fintrack-mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - fintrack-db-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  fintrack-db-data:
    driver: local
